### ISSUE TITLE
https imports broken

### ISSUE THREAD

**Issue by Divide-By-0** [0xPARC/zkrepl#8]
example code, after uncommenting the second import, fails with this error:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/4804438/233410942-3b286ff2-f512-4cac-a82e-41db9ef0e4bf.png">

**Comment by sigmachirality** [comment]
Looks like it was fixed in commit https://github.com/0xPARC/zkrepl/commit/1e8d06d3587bc75eacfa9caa259cce2a0e387f58
